import {Router} from 'express'; import {db} from '../db.js'; import {hashPassword,checkPassword,signUser,auth} from '../auth.js';
import {getAuth as getFirebaseAuth} from 'firebase-admin/auth';
import {initializeApp,cert,getApps} from 'firebase-admin/app';
const r=Router();
function firebaseAdmin(){
  if(!getApps().length){
    const raw=process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
    if(raw){const s=JSON.parse(raw);initializeApp({credential:cert(s)});}else if(process.env.FIREBASE_PROJECT_ID&&process.env.FIREBASE_CLIENT_EMAIL&&process.env.FIREBASE_PRIVATE_KEY){initializeApp({credential:cert({projectId:process.env.FIREBASE_PROJECT_ID,clientEmail:process.env.FIREBASE_CLIENT_EMAIL,privateKey:process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g,'\n')})});}else throw new Error('Firebase Admin is not configured');
  } return getFirebaseAuth();
}
r.post('/register',(req,res)=>{const {name,email,password}=req.body||{}; if(!name||!email||!password||password.length<6)return res.status(400).json({error:'Name, valid email and 6+ character password required'}); try{const info=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name,email.toLowerCase(),hashPassword(password)); const u=db.prepare('SELECT id,name,email,role,phone,phone_verified FROM users WHERE id=?').get(info.lastInsertRowid); res.status(201).json({user:u,token:signUser(u)});}catch(e){res.status(409).json({error:'Email already registered'});}});
r.post('/login',(req,res)=>{const {email,password}=req.body||{}; const u=db.prepare('SELECT * FROM users WHERE email=?').get((email||'').toLowerCase()); if(!u||!checkPassword(password||'',u.password_hash))return res.status(401).json({error:'Invalid email or password'}); const safe={id:u.id,name:u.name,email:u.email,role:u.role,phone:u.phone,phone_verified:!!u.phone_verified}; res.json({user:safe,token:signUser(safe)});});
r.post('/firebase',async(req,res)=>{try{const {idToken}=req.body||{};if(!idToken)return res.status(400).json({error:'Firebase ID token required'});const decoded=await firebaseAdmin().verifyIdToken(idToken);const uid=decoded.uid;const email=(decoded.email||`${uid}@phone.fashionoid.local`).toLowerCase();const name=decoded.name||decoded.email?.split('@')[0]||'FASHIONOID Customer';const phone=decoded.phone_number||null;let u=db.prepare('SELECT * FROM users WHERE firebase_uid=?').get(uid);if(!u)u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(u){db.prepare('UPDATE users SET firebase_uid=?,name=?,email=?,phone=?,phone_verified=? WHERE id=?').run(uid,name,email,phone,phone?1:0,u.id);u=db.prepare('SELECT * FROM users WHERE id=?').get(u.id)}else{const info=db.prepare('INSERT INTO users(name,email,password_hash,firebase_uid,phone,phone_verified) VALUES(?,?,?,?,?,?)').run(name,email,'',uid,phone,phone?1:0);u=db.prepare('SELECT * FROM users WHERE id=?').get(info.lastInsertRowid)}const safe={id:u.id,name:u.name,email:u.email,role:u.role,phone:u.phone,phone_verified:!!u.phone_verified};res.json({user:safe,token:signUser(safe)})}catch(e){console.error(e);res.status(401).json({error:'Firebase authentication failed'})}});
r.get('/me',auth,(req,res)=>res.json({user:db.prepare('SELECT id,name,email,role,created_at,phone,phone_verified FROM users WHERE id=?').get(req.user.id)}));
export default r;
