import {Router} from 'express'; import crypto from 'crypto'; import {db} from '../db.js'; import {auth,admin} from '../auth.js';
const r=Router(); const number=()=>`FNO-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString('hex').toUpperCase()}`;
r.post('/',auth,(req,res)=>{const {customer_name,phone,address,city,pincode,payment_method='COD',items=[]}=req.body||{};if(!customer_name||!phone||!address||!city||!pincode||!items.length)return res.status(400).json({error:'Complete address and at least one item are required'});const tx=db.transaction(()=>{let subtotal=0,rows=[];for(const i of items){const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(i.product_id);if(!p)throw Error(`Product ${i.product_id} not found`);if(p.stock<i.quantity)throw Error(`${p.name} has only ${p.stock} left`);subtotal+=p.price*i.quantity;rows.push({p,i});}const ord=number();const info=db.prepare('INSERT INTO orders(order_number,user_id,customer_name,phone,address,city,pincode,payment_method,subtotal,total) VALUES(?,?,?,?,?,?,?,?,?,?)').run(ord,req.user.id,customer_name,phone,address,city,pincode,payment_method,subtotal,subtotal);for(const {p,i} of rows){db.prepare('INSERT INTO order_items(order_id,product_id,name,sku,quantity,price,size,color,image) VALUES(?,?,?,?,?,?,?,?,?)').run(info.lastInsertRowid,p.id,p.name,p.sku,i.quantity,p.price,i.size||'',i.color||'',p.image);db.prepare('UPDATE products SET stock=stock-? WHERE id=?').run(i.quantity,p.id);}db.prepare('INSERT INTO order_events(order_id,status,note) VALUES(?,?,?)').run(info.lastInsertRowid,'placed','Order placed');return db.prepare('SELECT * FROM orders WHERE id=?').get(info.lastInsertRowid)});try{res.status(201).json(tx());}catch(e){res.status(400).json({error:e.message});}});
r.get('/mine',auth,(req,res)=>res.json(db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)));
r.get('/:id',auth,(req,res)=>{const o=db.prepare('SELECT * FROM orders WHERE id=?').get(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});if(req.user.role!=='admin'&&o.user_id!==req.user.id)return res.status(403).json({error:'Forbidden'});o.items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);o.events=db.prepare('SELECT * FROM order_events WHERE order_id=? ORDER BY created_at').all(o.id);res.json(o);});
r.get('/track/:number',(req,res)=>{const o=db.prepare('SELECT order_number,order_status,payment_status,created_at FROM orders WHERE order_number=?').get(req.params.number);if(!o)return res.status(404).json({error:'Order not found'});o.events=db.prepare('SELECT status,note,created_at FROM order_events WHERE order_id=(SELECT id FROM orders WHERE order_number=?) ORDER BY created_at').all(req.params.number);res.json(o);});
r.patch('/:id/status',auth,admin,(req,res)=>{const {status,note=''}=req.body||{};const allowed=['placed','confirmed','packed','shipped','out_for_delivery','delivered','cancelled'];if(!allowed.includes(status))return res.status(400).json({error:'Invalid status'});db.prepare('UPDATE orders SET order_status=? WHERE id=?').run(status,req.params.id);db.prepare('INSERT INTO order_events(order_id,status,note) VALUES(?,?,?)').run(req.params.id,status,note);res.json({ok:true});});
r.get('/',auth,admin,(req,res)=>res.json(db.prepare('SELECT * FROM orders ORDER BY created_at DESC').all()));
export default r;
