import {Router} from 'express'; import {db} from '../db.js'; import {auth,admin} from '../auth.js';
const r=Router();
const parse=p=>({...p,sizes:JSON.parse(p.sizes||'[]'),colors:JSON.parse(p.colors||'[]'),active:Boolean(p.active),discount:p.compare_price&&p.compare_price>p.price?Math.round((1-p.price/p.compare_price)*100):0});
r.get('/',(req,res)=>{const {category,search,limit=50}=req.query; let sql='SELECT * FROM products WHERE active=1',args=[]; if(category){sql+=' AND category=?';args.push(category)} if(search){sql+=' AND (name LIKE ? OR sku LIKE ?)';args.push('%'+search+'%','%'+search+'%')} sql+=' ORDER BY created_at DESC LIMIT ?';args.push(Math.min(Number(limit)||50,100)); res.json(db.prepare(sql).all(...args).map(parse));});
r.get('/admin/all',auth,admin,(req,res)=>{const {category,search,limit=100}=req.query; let sql='SELECT * FROM products WHERE 1=1',args=[]; if(category&&category!=='All'){sql+=' AND category=?';args.push(category)} if(search){sql+=' AND (name LIKE ? OR sku LIKE ?)';args.push('%'+search+'%','%'+search+'%')} sql+=' ORDER BY created_at DESC LIMIT ?';args.push(Math.min(Number(limit)||100,200)); res.json(db.prepare(sql).all(...args).map(parse));});
r.get('/:id',(req,res)=>{const p=db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id); if(!p)return res.status(404).json({error:'Product not found'});res.json(parse(p));});
r.post('/',auth,admin,(req,res)=>{const p=req.body||{};try{const info=db.prepare('INSERT INTO products(sku,name,category,description,price,compare_price,stock,image,sizes,colors) VALUES(?,?,?,?,?,?,?,?,?,?)').run(p.sku,p.name,p.category,p.description||'',p.price,p.compare_price||null,p.stock||0,p.image||'',JSON.stringify(p.sizes||[]),JSON.stringify(p.colors||[]));res.status(201).json(parse(db.prepare('SELECT * FROM products WHERE id=?').get(info.lastInsertRowid)));}catch(e){res.status(400).json({error:e.message});}});
r.patch('/:id',auth,admin,(req,res)=>{const old=db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id);if(!old)return res.status(404).json({error:'Product not found'});const p={...parse(old),...req.body};db.prepare('UPDATE products SET name=?,category=?,description=?,price=?,compare_price=?,stock=?,image=?,sizes=?,colors=?,active=? WHERE id=?').run(p.name,p.category,p.description,p.price,p.compare_price||null,p.stock,p.image||'',JSON.stringify(p.sizes||[]),JSON.stringify(p.colors||[]),p.active?1:0,req.params.id);res.json(parse(db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id)));});
export default r;
