import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import {db} from './db.js';
import auth from './routes/auth.js';
import products from './routes/products.js';
import orders from './routes/orders.js';
import admin from './routes/admin.js';
import payments from './routes/payments.js';

const app=express();
const origins=(process.env.FRONTEND_ORIGIN||'').split(',').map(s=>s.trim()).filter(Boolean);
app.disable('x-powered-by');
app.set('trust proxy',1);
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(cors({origin:(origin,cb)=>{if(!origin||origins.length===0||origins.includes(origin)) return cb(null,true); cb(new Error('CORS origin not allowed'));},credentials:true}));
app.use(express.json({limit:'1mb'}));
app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:'draft-8',legacyHeaders:false}));
app.get('/api/health',(req,res)=>res.json({ok:true,brand:'FASHIONOID',status:'production-ready',time:new Date().toISOString()}));
app.use('/api/auth',auth);
app.use('/api/products',products);
app.use('/api/orders',orders);
app.use('/api/admin',admin);
app.use('/api/payments',payments);
app.use((req,res)=>res.status(404).json({error:'Route not found'}));
app.use((err,req,res,next)=>{console.error(err); const status=err.status||500; res.status(status).json({error:status===500?'Server error':err.message});});
const port=process.env.PORT||4000;
app.listen(port,()=>console.log(`FASHIONOID API running on port ${port}`));
